# Generated by Django 3.0.6 on 2020-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20150509_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
